from aoc_2022.day_23.b import get_solution, solve

SAMPLE_DATA = """
..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............
"""


def test_solve():
    assert solve(SAMPLE_DATA) == 20


def test_my_solution():
    assert get_solution() == 1005
