version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest
  build-and-check-formatting:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Check formatting with black
          command: poetry run black --check . --target-version py310
  build-and-check-import-sorting:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Check formatting with black
          command: poetry run isort . --check
  build-and-check-lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Lint with flake8
          command: poetry run flake8 .
  build-and-typecheck:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Typecheck the dang thing
          command: poetry run pyright
workflows:
  test:
    jobs:
      - build-and-test
  check-formatting:
    jobs:
      - build-and-check-formatting
      - build-and-check-import-sorting
      - build-and-check-lint
  typecheck:
    jobs:
      - build-and-typecheck
